name: Metrics
on:
  # Schedule updates (daily at midnight Cairo time, approx 22:00 UTC)
  schedule: [{cron: "0 22 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: YoussefMoHlemyAlpha
          template: classic
          base: ""
          filename: metrics.achievements.svg
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

      - name: Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: YoussefMoHlemyAlpha
          template: classic
          base: ""
          filename: metrics.isocalendar.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
