name: Metrics
on:
  # Schedule updates (daily at midnight Cairo time, approx 22:00 UTC)
  schedule: [{cron: "0 22 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: YoussefMoHlemyAlpha
          template: classic
          base: ""
          filename: metrics.isocalendar.purple.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_isocalendar_colors: "*, #800080"
